const QUIZ = {
  title: "Essential Grammar — Units 13-20 Quiz",
  totalQuestions: 100,
  questions: [
    // Unit 1: am/is/are (1-8)
    // { unit: 1, q: "Choose the correct sentence.", options: ["She are happy.", "She is happy.", "She am happy.", "She be happy."], answer: 1 },
    // { unit: 1, q: "They ___ from Brazil.", options: ["is", "am", "are", "be"], answer: 2 },
    // { unit: 1, q: "I ___ not hungry.", options: ["is", "am", "are", "be"], answer: 1 },
    // { unit: 1, q: "It ___ cold today.", options: ["are", "am", "is", "be"], answer: 2 },
    // { unit: 1, q: "My keys ___ on the table.", options: ["is", "am", "are", "be"], answer: 2 },
    // { unit: 1, q: "He ___ a doctor.", options: ["are", "is", "am", "be"], answer: 1 },
    // { unit: 1, q: "We ___ good friends.", options: ["is", "am", "are", "be"], answer: 2 },
    // { unit: 1, q: "The weather ___ nice, but it ___ not warm.", options: ["is / is", "are / are", "is / isn't", "are / isn't"], answer: 2 },

    // Unit 2: am/is/are questions (9-16)
    // { unit: 2, q: "___ you from Canada?", options: ["Is", "Are", "Am", "Do"], answer: 1 },
    // { unit: 2, q: "Where ___ your mother?", options: ["are", "is", "am", "do"], answer: 1 },
    // { unit: 2, q: "___ they new shoes?", options: ["Is", "Are", "Am", "Do"], answer: 1 },
    // { unit: 2, q: "How old ___ she?", options: ["are", "is", "am", "do"], answer: 1 },
    // { unit: 2, q: "Short answer: 'Are you tired?' — 'Yes, ___ .'", options: ["I am", "I'm", "you are", "she is"], answer: 0 },
    // { unit: 2, q: "Short answer: 'Is it cold?' — 'No, ___ .'", options: ["it not", "it isn't", "isn't it", "not it"], answer: 1 },
    // { unit: 2, q: "___ colour is your car?", options: ["Where", "What", "How", "Who"], answer: 1 },
    // { unit: 2, q: "___ your parents at home?", options: ["Is", "Are", "Am", "Do"], answer: 1 },

    // Unit 3: present continuous (17-24)
    // { unit: 3, q: "Listen! Somebody ___ .", options: ["sing", "sings", "is singing", "are singing"], answer: 2 },
    // { unit: 3, q: "She ___ an apple right now.", options: ["eats", "is eating", "eat", "are eating"], answer: 1 },
    // { unit: 3, q: "They ___ football at the moment.", options: ["is playing", "plays", "are playing", "play"], answer: 2 },
    // { unit: 3, q: "It ___ today.", options: ["rain", "rains", "is raining", "are raining"], answer: 2 },
    // { unit: 3, q: "I ___ TV. You can turn it off.", options: ["don't watch", "am not watching", "not watch", "doesn't watch"], answer: 1 },
    // { unit: 3, q: "The children ___ their homework now.", options: ["is doing", "does", "are doing", "do"], answer: 2 },
    // { unit: 3, q: "Correct spelling: run → ___", options: ["runing", "running", "runned", "runs"], answer: 1 },
    // { unit: 3, q: "Please be quiet. I ___ .", options: ["work", "am working", "works", "working"], answer: 1 },

    // Unit 4: present continuous questions (25-32)
    // { unit: 4, q: "___ it raining?", options: ["Does", "Is", "Are", "Do"], answer: 1 },
    // { unit: 4, q: "What ___ the children doing?", options: ["is", "are", "am", "do"], answer: 1 },
    // { unit: 4, q: "Why ___ you wearing a coat?", options: ["do", "are", "is", "does"], answer: 1 },
    // { unit: 4, q: "___ Ben working today?", options: ["Do", "Does", "Is", "Are"], answer: 2 },
    // { unit: 4, q: "Where ___ she going?", options: ["do", "does", "is", "are"], answer: 2 },
    // { unit: 4, q: "Short answer: 'Are you going now?' — 'Yes, ___ .'", options: ["I do", "I am", "you are", "I'm not"], answer: 1 },
    // { unit: 4, q: "Short answer: 'Is it raining?' — 'No, ___ .'", options: ["it isn't", "it not", "doesn't", "isn't it"], answer: 0 },
    // { unit: 4, q: "Who ___ you waiting for?", options: ["do", "are", "is", "does"], answer: 1 },

    // Unit 5: present simple (33-40)
    // { unit: 5, q: "She ___ in London.", options: ["live", "lives", "living", "is live"], answer: 1 },
    // { unit: 5, q: "They ___ a lot of books.", options: ["has", "have", "having", "is have"], answer: 1 },
    // { unit: 5, q: "It ___ a lot in winter.", options: ["rain", "rains", "is raining", "are raining"], answer: 1 },
    // { unit: 5, q: "He ___ at 7.30 every morning.", options: ["start", "starts", "starting", "is start"], answer: 1 },
    // { unit: 5, q: "The earth ___ round the sun.", options: ["go", "goes", "going", "is go"], answer: 1 },
    // { unit: 5, q: "I ___ breakfast.", options: ["never eat", "eat never", "never eats", "does never eat"], answer: 0 },
    // { unit: 5, q: "She always ___ early.", options: ["arrive", "arrives", "arriving", "is arrive"], answer: 1 },
    // { unit: 5, q: "Correct form: study → he ___", options: ["studys", "study", "studies", "studying"], answer: 2 },

    // Unit 6: present simple negative (41-48)
    // { unit: 6, q: "I ___ coffee.", options: ["don't like", "doesn't like", "not like", "don't likes"], answer: 0 },
    // { unit: 6, q: "She ___ meat.", options: ["don't eat", "doesn't eat", "not eat", "doesn't eats"], answer: 1 },
    // { unit: 6, q: "They ___ TV very often.", options: ["doesn't watch", "don't watch", "not watch", "don't watches"], answer: 1 },
    // { unit: 6, q: "It ___ much here.", options: ["don't rain", "doesn't rain", "not rain", "doesn't rains"], answer: 1 },
    // { unit: 6, q: "My car ___ much petrol.", options: ["don't use", "doesn't use", "not use", "doesn't uses"], answer: 1 },
    // { unit: 6, q: "We ___ many people.", options: ["doesn't know", "don't know", "not know", "don't knows"], answer: 1 },
    // { unit: 6, q: "He ___ breakfast.", options: ["doesn't usually have", "don't usually have", "doesn't usually has", "not usually have"], answer: 0 },
    // { unit: 6, q: "I ___ football.", options: ["don't like", "doesn't like", "am not like", "not like"], answer: 0 },

    // // Unit 7: present simple questions (49-56)
    // { unit: 7, q: "___ you speak English?", options: ["Does", "Do", "Are", "Is"], answer: 1 },
    // { unit: 7, q: "___ she work on Sundays?", options: ["Do", "Does", "Is", "Are"], answer: 1 },
    // { unit: 7, q: "Where ___ they live?", options: ["do", "does", "is", "are"], answer: 0 },
    // { unit: 7, q: "What ___ you do? (= What's your job?)", options: ["are", "do", "does", "is"], answer: 1 },
    // { unit: 7, q: "How often ___ you wash your hair?", options: ["do", "does", "are", "is"], answer: 0 },
    // { unit: 7, q: "Short answer: 'Do you play the guitar?' — 'No, ___ .'", options: ["I don't", "I not", "I doesn't", "don't I"], answer: 0 },
    // { unit: 7, q: "Short answer: 'Does James work hard?' — 'Yes, ___ .'", options: ["he do", "he does", "he is", "does he"], answer: 1 },
    // { unit: 7, q: "___ it cost a lot?", options: ["Do", "Does", "Is", "Are"], answer: 1 },

    // Unit 8: continuous vs simple (57-64)
    // { unit: 8, q: "I ___ every day from 9 to 5.", options: ["am working", "work", "working", "am work"], answer: 1 },
    // { unit: 8, q: "Shhh! I ___ now.", options: ["work", "am working", "works", "working"], answer: 1 },
    // { unit: 8, q: "She ___ tennis every Sunday.", options: ["is playing", "plays", "play", "playing"], answer: 1 },
    // { unit: 8, q: "Look! She ___ tennis.", options: ["plays", "is playing", "play", "playing"], answer: 1 },
    // { unit: 8, q: "I ___ to go home. (want)", options: ["am wanting", "want", "wants", "am want"], answer: 1 },
    // { unit: 8, q: "___ you know that man?", options: ["Are", "Do", "Does", "Is"], answer: 1 },
    // { unit: 8, q: "It ___ a lot in winter.", options: ["is raining", "rains", "rain", "are raining"], answer: 1 },
    // { unit: 8, q: "Take an umbrella. It ___ .", options: ["rains", "is raining", "rain", "are raining"], answer: 1 },

    // Unit 9: have / have got (65-72)
    // { unit: 9, q: "She ___ two brothers.", options: ["have", "has", "having", "is have"], answer: 1 },
    // { unit: 9, q: "I ___ got a car.", options: ["has", "have", "having", "am"], answer: 1 },
    // { unit: 9, q: "They ___ any children.", options: ["don't have", "doesn't have", "hasn't", "isn't have"], answer: 0 },
    // { unit: 9, q: "___ you got a pen?", options: ["Has", "Have", "Do", "Does"], answer: 1 },
    // { unit: 9, q: "He ___ a headache.", options: ["have got", "has got", "have", "having"], answer: 1 },
    // { unit: 9, q: "She ___ a job at the moment.", options: ["doesn't have", "don't have", "not have", "doesn't has"], answer: 0 },
    // { unit: 9, q: "We ___ a lot of work to do.", options: ["has", "have", "having", "is have"], answer: 1 },
    // { unit: 9, q: "___ Helen got a car?", options: ["Do", "Does", "Has", "Have"], answer: 2 },

    // Unit 10: was/were (73-80)
    // { unit: 10, q: "I ___ tired last night.", options: ["was", "were", "am", "is"], answer: 0 },
    // { unit: 10, q: "They ___ at home yesterday.", options: ["was", "were", "are", "is"], answer: 1 },
    // { unit: 10, q: "___ the weather nice last week?", options: ["Was", "Were", "Is", "Are"], answer: 0 },
    // { unit: 10, q: "She ___ 22 last year.", options: ["was", "were", "is", "are"], answer: 0 },
    // { unit: 10, q: "We ___ hungry after the journey.", options: ["was", "were", "are", "is"], answer: 1 },
    // { unit: 10, q: "Short answer: 'Were you late?' — 'No, ___ .'", options: ["I wasn't", "I weren't", "I not", "wasn't I"], answer: 0 },
    // { unit: 10, q: "Where ___ you at 3 o'clock?", options: ["was", "were", "are", "is"], answer: 1 },
    // { unit: 10, q: "The hotel ___ comfortable, but it ___ expensive.", options: ["was / wasn't", "were / weren't", "was / weren't", "were / wasn't"], answer: 0 },

    // Unit 11: past simple (81-90)
    // { unit: 11, q: "Yesterday I ___ to the cinema.", options: ["go", "went", "goes", "going"], answer: 1 },
    // { unit: 11, q: "She ___ her teeth this morning.", options: ["cleaned", "clean", "cleans", "cleaning"], answer: 0 },
    // { unit: 11, q: "We ___ the party last night.", options: ["enjoyed", "enjoy", "enjoys", "enjoying"], answer: 0 },
    // { unit: 11, q: "He ___ up at 6 o'clock.", options: ["get", "got", "gets", "getting"], answer: 1 },
    // { unit: 11, q: "They ___ home late.", options: ["come", "came", "comes", "coming"], answer: 1 },
    // { unit: 11, q: "I ___ a new phone last week.", options: ["buyed", "bought", "buy", "buys"], answer: 1 },
    // { unit: 11, q: "She ___ very well.", options: ["singed", "sang", "sing", "sings"], answer: 1 },
    // { unit: 11, q: "We ___ a lot of work yesterday.", options: ["did", "do", "does", "done"], answer: 0 },
    // { unit: 11, q: "He ___ the window because it was hot.", options: ["opened", "open", "opens", "opening"], answer: 0 },
    // { unit: 11, q: "Past of 'see' is ___", options: ["seed", "saw", "seen", "see"], answer: 1 },

    // // Unit 12: past negative & questions (91-100)
    // { unit: 12, q: "I ___ TV yesterday.", options: ["didn't watch", "didn't watched", "don't watch", "not watch"], answer: 0 },
    // { unit: 12, q: "She ___ to the bank.", options: ["didn't go", "didn't went", "doesn't go", "not go"], answer: 0 },
    // { unit: 12, q: "___ you enjoy the film?", options: ["Do", "Did", "Were", "Was"], answer: 1 },
    // { unit: 12, q: "What ___ you do last night?", options: ["do", "did", "does", "were"], answer: 1 },
    // { unit: 12, q: "They ___ the shopping.", options: ["didn't do", "didn't did", "don't do", "not do"], answer: 0 },
    // { unit: 12, q: "Short answer: 'Did it rain?' — 'Yes, ___ .'", options: ["it did", "it does", "it was", "did it"], answer: 0 },
    // { unit: 12, q: "Short answer: 'Did she come?' — 'No, ___ .'", options: ["she didn't", "she don't", "she wasn't", "didn't she"], answer: 0 },
    // { unit: 12, q: "Where ___ they go on holiday?", options: ["do", "did", "were", "does"], answer: 1 },
    // { unit: 12, q: "He ___ time to phone.", options: ["didn't have", "didn't had", "doesn't have", "not have"], answer: 0 },
    // { unit: 12, q: "We went out, but we ___ the food.", options: ["didn't enjoy", "didn't enjoyed", "don't enjoy", "not enjoy"], answer: 0 }

    // Unit 13: Past Continuous (1–13)
      { unit: 13, q: "At 8 o'clock last night, I ___ TV.", options: ["watched", "was watching", "have watched", "watch"], answer: 1 },
      { unit: 13, q: "She ___ dinner when I arrived.", options: ["cooked", "was cooking", "has cooked", "cooks"], answer: 1 },
      { unit: 13, q: "They ___ football at 5 p.m. yesterday.", options: ["played", "were playing", "have played", "play"], answer: 1 },
      { unit: 13, q: "It ___ when we left the house.", options: ["rained", "was raining", "has rained", "rains"], answer: 1 },
      { unit: 13, q: "I ___ a book at that time.", options: ["read", "was reading", "have read", "am reading"], answer: 1 },
      { unit: 13, q: "The children ___ outside all afternoon.", options: ["played", "were playing", "have played", "play"], answer: 1 },
      { unit: 13, q: "What ___ you doing at 10 o'clock last night?", options: ["did", "were", "was", "have"], answer: 1 },
      { unit: 13, q: "___ she sleeping when you called?", options: ["Did", "Was", "Is", "Has"], answer: 1 },
      { unit: 13, q: "We ___ for the bus at 7 this morning.", options: ["waited", "were waiting", "have waited", "wait"], answer: 1 },
      { unit: 13, q: "The baby ___ because it was hungry.", options: ["cried", "was crying", "has cried", "cries"], answer: 1 },
      { unit: 13, q: "Why ___ they laughing?", options: ["did", "were", "was", "have"], answer: 1 },
      { unit: 13, q: "Short answer: 'Were you working?' — 'Yes, ___ .'", options: ["I was", "I were", "I did", "I am"], answer: 0 },
      { unit: 13, q: "Short answer: 'Was it snowing?' — 'No, ___ .'", options: ["it wasn't", "it weren't", "it didn't", "it isn't"], answer: 0 },
      // Unit 14: Past Continuous vs Past Simple (14–26)
      { unit: 14, q: "While I ___ dinner, the phone rang.", options: ["cooked", "was cooking", "have cooked", "cook"], answer: 1 },
      { unit: 14, q: "They ___ football when it started to rain.", options: ["played", "were playing", "have played", "play"], answer: 1 },
      { unit: 14, q: "I ___ when I heard a loud noise.", options: ["walked", "was walking", "have walked", "walk"], answer: 1 },
      { unit: 14, q: "She ___ a book when her friend arrived.", options: ["read", "was reading", "has read", "reads"], answer: 1 },
      { unit: 14, q: "The children ___ outside when their mother called them.", options: ["played", "were playing", "have played", "play"], answer: 1 },
      { unit: 14, q: "We ___ TV when the lights went out.", options: ["watched", "were watching", "have watched", "watch"], answer: 1 },
      { unit: 14, q: "He ___ into the room while we were talking.", options: ["came", "comes", "was coming", "has come"], answer: 0 },
      { unit: 14, q: "When I saw Anna, she ___ for the bus.", options: ["waited", "was waiting", "has waited", "waits"], answer: 1 },
      { unit: 14, q: "I dropped my phone while I ___.", options: ["ran", "was running", "have run", "run"], answer: 1 },
      { unit: 14, q: "The teacher arrived while the students ___.", options: ["talked", "were talking", "have talked", "talk"], answer: 1 },
      { unit: 14, q: "What ___ you doing when the accident happened?", options: ["did", "were", "was", "have"], answer: 1 },
      { unit: 14, q: "Short answer: 'Were they sleeping when you called?' — 'Yes, ___ .'", options: ["they were", "they did", "they are", "they have"], answer: 0 },
      { unit: 14, q: "Choose the correct sentence.", options: ["I was watching TV when Tom called.", "I watched TV when Tom was calling.", "I was watch TV when Tom called.", "I watching TV when Tom called."], answer: 0 },
      // Unit 15: Present Perfect (27–39)
      { unit: 15, q: "She ___ her homework.", options: ["finished", "has finished", "finishes", "finish"], answer: 1 },
      { unit: 15, q: "I ___ my keys.", options: ["have lost", "lost", "lose", "am losing"], answer: 0 },
      { unit: 15, q: "They ___ to the station.", options: ["have gone", "went", "go", "are going"], answer: 0 },
      { unit: 15, q: "We ___ the film. It was great!", options: ["have seen", "saw", "see", "are seeing"], answer: 0 },
      { unit: 15, q: "He ___ his lunch already.", options: ["has eaten", "ate", "eats", "is eating"], answer: 0 },
      { unit: 15, q: "The bus ___ .", options: ["has arrived", "arrived", "arrives", "is arriving"], answer: 0 },
      { unit: 15, q: "I can't find my phone. I think I ___ it.", options: ["have lost", "lost", "lose", "was losing"], answer: 0 },
      { unit: 15, q: "She ___ a new job.", options: ["has started", "started", "starts", "is starting"], answer: 0 },
      { unit: 15, q: "They ___ home.", options: ["have come", "came", "come", "are coming"], answer: 0 },
      { unit: 15, q: "Choose the correct sentence.", options: ["He has broken his leg.", "He has broke his leg.", "He broken his leg.", "He is break his leg."], answer: 0 },
      { unit: 15, q: "Short answer: 'Have you finished your work?' — 'Yes, ___ .'", options: ["I have", "I did", "I am", "I do"], answer: 0 },
      { unit: 15, q: "Short answer: 'Has she gone home?' — 'No, ___ .'", options: ["she hasn't", "she didn't", "she isn't", "she doesn't"], answer: 0 },
      { unit: 15, q: "Which sentence uses the present perfect correctly?", options: ["I've lost my wallet.", "I lost my wallet now.", "I'm losing my wallet yesterday.", "I have lose my wallet."], answer: 0 },
      // Unit 16: Present Perfect (2) - just / already / yet (40–52)
      { unit: 16, q: "I've ___ finished my homework.", options: ["yet", "already", "just", "ago"], answer: 2 },
      { unit: 16, q: "She has ___ gone home.", options: ["already", "yet", "ago", "last"], answer: 0 },
      { unit: 16, q: "Have you finished your homework ___?", options: ["already", "just", "yet", "ago"], answer: 2 },
      { unit: 16, q: "They haven't arrived ___.", options: ["already", "just", "yet", "last"], answer: 2 },
      { unit: 16, q: "We have ___ eaten lunch.", options: ["just", "yesterday", "last", "ago"], answer: 0 },
      { unit: 16, q: "The film has ___ started.", options: ["yet", "already", "tomorrow", "last"], answer: 1 },
      { unit: 16, q: "I haven't read that book ___.", options: ["already", "just", "yet", "before"], answer: 2 },
      { unit: 16, q: "Choose the correct sentence.", options: ["I've just seen Tom.", "I just have seen Tom.", "I've seen just Tom.", "I have yesterday seen Tom."], answer: 0 },
      { unit: 16, q: "Choose the correct sentence.", options: ["Has the train left yet?", "Has yet the train left?", "Did the train leave yet?", "Has the train left already yet?"], answer: 0 },
      { unit: 16, q: "Short answer: 'Have they arrived yet?' — 'No, ___ .'", options: ["they haven't", "they don't", "they didn't", "they aren't"], answer: 0 },
      { unit: 16, q: "Short answer: 'Has she already eaten?' — 'Yes, ___ .'", options: ["she has", "she is", "she did", "she does"], answer: 0 },
      { unit: 16, q: "I can't go out. I've ___ cleaned my room.", options: ["already", "yet", "ago", "last"], answer: 0 },
      { unit: 16, q: "Which sentence is correct?", options: ["I haven't finished yet.", "I didn't finish yet.", "I haven't finished already.", "I not finished yet."], answer: 0 },
      // Unit 17: Have you ever...? (53–64)
      { unit: 17, q: "___ you ever been to Thailand?", options: ["Did", "Have", "Has", "Were"], answer: 1 },
      { unit: 17, q: "She ___ never flown in a plane.", options: ["has", "have", "did", "was"], answer: 0 },
      { unit: 17, q: "Have you ever ___ sushi?", options: ["eat", "ate", "eaten", "eating"], answer: 2 },
      { unit: 17, q: "He has ___ seen snow before.", options: ["ever", "never", "yet", "just"], answer: 1 },
      { unit: 17, q: "___ Tom ever visited London?", options: ["Did", "Has", "Have", "Was"], answer: 1 },
      { unit: 17, q: "I have never ___ a horse.", options: ["ride", "rode", "ridden", "riding"], answer: 2 },
      { unit: 17, q: "Have they ever ___ that movie?", options: ["see", "saw", "seen", "seeing"], answer: 2 },
      { unit: 17, q: "Choose the correct sentence.", options: ["I've never been to Japan.", "I never have been to Japan.", "I didn't never go to Japan.", "I've never went to Japan."], answer: 0 },
      { unit: 17, q: "Choose the correct question.", options: ["Have you ever met a famous person?", "Did you ever met a famous person?", "Have you ever meet a famous person?", "Were you ever meet a famous person?"], answer: 0 },
      { unit: 17, q: "Short answer: 'Have you ever been to Bagan?' — 'Yes, ___ .'", options: ["I have", "I did", "I was", "I do"], answer: 0 },
      { unit: 17, q: "Short answer: 'Has she ever tried Chinese food?' — 'No, ___ .'", options: ["she hasn't", "she didn't", "she doesn't", "she isn't"], answer: 0 },
      { unit: 17, q: "Which sentence is correct?", options: ["Have you ever lost your phone?", "Did you ever lost your phone?", "Have you ever lose your phone?", "Were you ever lose your phone?"], answer: 0 },
      // Unit 18: How long have you...? (65–76)
      { unit: 18, q: "How long ___ you lived here?", options: ["did", "have", "do", "are"], answer: 1 },
      { unit: 18, q: "She ___ in Yangon for five years.", options: ["lives", "has lived", "lived", "is living"], answer: 1 },
      { unit: 18, q: "We ___ each other since 2020.", options: ["know", "knew", "have known", "are knowing"], answer: 2 },
      { unit: 18, q: "He ___ at this company for two years.", options: ["worked", "works", "has worked", "is working"], answer: 2 },
      { unit: 18, q: "I ___ this book for a long time.", options: ["have had", "had", "have", "am having"], answer: 0 },
      { unit: 18, q: "How long has Anna ___ English?", options: ["study", "studied", "studies", "studying"], answer: 1 },
      { unit: 18, q: "They ___ married since 2018.", options: ["are", "were", "have been", "been"], answer: 2 },
      { unit: 18, q: "Choose the correct sentence.", options: ["I've lived here for three years.", "I live here for three years.", "I've lived here since three years.", "I lived here since three years."], answer: 0 },
      { unit: 18, q: "How long ___ your brother had his car?", options: ["does", "did", "has", "is"], answer: 2 },
      { unit: 18, q: "Short answer: 'Have you known Tom for a long time?' — 'Yes, ___ .'", options: ["I have", "I do", "I did", "I am"], answer: 0 },
      { unit: 18, q: "Short answer: 'Has she worked here since January?' — 'No, ___ .'", options: ["she hasn't", "she doesn't", "she didn't", "she isn't"], answer: 0 },
      { unit: 18, q: "Which sentence is correct?", options: ["We've been friends for many years.", "We are friends since many years.", "We have friends for many years.", "We were friends since many years."], answer: 0 },
      // Unit 19: for / since / ago (77–88)
      { unit: 19, q: "I have lived here ___ five years.", options: ["since", "for", "ago", "from"], answer: 1 },
      { unit: 19, q: "She has worked here ___ 2022.", options: ["for", "since", "ago", "during"], answer: 1 },
      { unit: 19, q: "We met three years ___.", options: ["for", "since", "ago", "before"], answer: 2 },
      { unit: 19, q: "They have known each other ___ a long time.", options: ["since", "for", "ago", "from"], answer: 1 },
      { unit: 19, q: "I've had this phone ___ last June.", options: ["for", "since", "ago", "during"], answer: 1 },
      { unit: 19, q: "He left school two years ___.", options: ["since", "for", "ago", "during"], answer: 2 },
      { unit: 19, q: "Choose the correct sentence.", options: ["I've been here since Monday.", "I've been here for Monday.", "I've been here ago Monday.", "I've been here from Monday."], answer: 0 },
      { unit: 19, q: "Choose the correct sentence.", options: ["She has lived in Mandalay for ten years.", "She has lived in Mandalay since ten years.", "She lived in Mandalay for ten years ago.", "She has lived in Mandalay ago ten years."], answer: 0 },
      { unit: 19, q: "We have been friends ___ we were children.", options: ["for", "since", "ago", "during"], answer: 1 },
      { unit: 19, q: "I started learning English six months ___.", options: ["for", "since", "ago", "already"], answer: 2 },
      { unit: 19, q: "Short answer: 'Have you lived here for a long time?' — 'Yes, ___ .'", options: ["I have", "I do", "I did", "I am"], answer: 0 },
      { unit: 19, q: "Which sentence is correct?", options: ["I've known her since 2021.", "I've known her for 2021.", "I know her since 2021.", "I knew her for 2021."], answer: 0 },
      // Unit 20: Present Perfect vs Past Simple (89–100)
      { unit: 20, q: "I ___ that movie yesterday.", options: ["have seen", "saw", "see", "have saw"], answer: 1 },
      { unit: 20, q: "She ___ to Japan three times.", options: ["went", "has been", "has gone", "was"], answer: 1 },
      { unit: 20, q: "___ you ever visited Bagan?", options: ["Did", "Have", "Were", "Do"], answer: 1 },
      { unit: 20, q: "When ___ you buy your new laptop?", options: ["have", "did", "do", "are"], answer: 1 },
      { unit: 20, q: "I ___ my homework, so I can go out now.", options: ["finished", "have finished", "finish", "was finishing"], answer: 1 },
      { unit: 20, q: "They ___ to the beach last weekend.", options: ["have gone", "went", "have been", "go"], answer: 1 },
      { unit: 20, q: "We ___ each other since we were children.", options: ["knew", "have known", "know", "are knowing"], answer: 1 },
      { unit: 20, q: "He ___ his keys yesterday.", options: ["has lost", "lost", "loses", "has lose"], answer: 1 },
      { unit: 20, q: "Choose the correct sentence.", options: ["I've just finished my lunch.", "I just finished my lunch now.", "I've finished my lunch yesterday.", "I have finish my lunch."], answer: 0 },
      { unit: 20, q: "Choose the correct sentence.", options: ["Did you see Anna yesterday?", "Have you seen Anna yesterday?", "Have you saw Anna yesterday?", "Did you seen Anna yesterday?"], answer: 0 },
      { unit: 20, q: "Short answer: 'Have you finished the book?' — 'Yes, ___ .'", options: ["I have", "I did", "I do", "I was"], answer: 0 },
      { unit: 20, q: "Short answer: 'Did Tom call you last night?' — 'No, ___ .'", options: ["he didn't", "he hasn't", "he doesn't", "he wasn't"], answer: 0 },
]
};
